# Generated by Django 5.2 on 2025-04-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anmeldung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorname', models.CharField(max_length=100)),
                ('nachname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('bemerkung', models.TextField(blank=True)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
