# Generated by Django 5.2 on 2025-06-23 16:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_remove_anmeldung_erstellt_am_anmeldung_ist_bezahlt_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("paid", models.BooleanField(default=False)),
                ("qr_code_token", models.UUIDField(default=uuid.uuid4, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="anmeldung",
            name="fahrzeugtyp",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
