# Generated by Django 5.2 on 2025-06-23 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_participant_alter_anmeldung_fahrzeugtyp"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="anmeldung",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.anmeldung",
            ),
        ),
    ]
