# Generated by Django 5.2.1 on 2025-06-25 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_participant_anmeldung"),
    ]

    operations = []
