# Generated by Django 5.2 on 2025-06-26 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_auto_20250625_1207"),
    ]

    operations = [
       # migrations.AddField(
        #    model_name="anmeldung",
         #   name="qr_code_url",
          #  field=models.URLField(blank=True, null=True),
        #),
        migrations.AlterField(
            model_name="participant",
            name="qr_code_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
